### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by MattMcFarland** [BerndWessels/babel-relay-plugin-loader#3]
This was a huge life saver for me.  Thanks a lot.  I didnt know how to thank you without opening an issue.

**Comment by BerndWessels** [comment]
No worries. Oh and be prepared, it looks like they will rename the `babel-relay-plugin` to `babel-plugin-relay` soon. So I might do the same with the loader.
Cheers
Bernd

**Comment by BerndWessels** [comment]
My shameless self-promotion here ;) Checkout [this repo](https://github.com/BerndWessels/react-webpack) for a complete example of react and relay in a real real-world example with SQL database and bootstrap UI.
