### ISSUE TITLE
The schema.json file is not registered as a dependency

### ISSUE THREAD

**Issue by guncha** [BerndWessels/babel-relay-plugin-loader#4]
I'm not 100% sure that this is exactly what's happening, but I'm seeing situations where Babel cache is out of date because of changes in the schema.json. It also looks like the `babel-relay-plugin` is not reloaded when the schema file changes, which is related to the above point. Does that seem to make sense?

**Comment by BerndWessels** [comment]
Are we talking about a specific project? In general I guess the loader plugin is invoked whenever webpack tells babel to build. But that does not mean that the schema.json has been updated automatically unless you have somehow triggered it yourself.
Thats all I can say at the moment until you provide a bit more details about the problem.
Cheers
Bernd

**Comment by guncha** [comment]
Thanks for getting back. Yes, in our project we're using Webpack in watch mode and when we switch branches that might have a different `schema.json`, babel throws a lot of errors because it's still using the same schema.

I created a sample repo trying to make it as minimal as possible. It's not using Webpack, but should be sufficient for demonstrating the issue:

https://gist.github.com/guncha/4cdd4d8464ffbc8dd918
1. Run babel-cli in watch mode using `npm run watch`
2. Change `schema.json` somehow

These changes are ignored by the compiler.

I suspect there's API for babel plugins to declare dependencies and be able to reload when they change, but I'm not too familiar with that.

**Comment by BerndWessels** [comment]
@guncha OK, I see. I will see what I can find out, but most likely after the weekend ;)

**Comment by guncha** [comment]
Thanks. I'd like to figure the Babel API, so I'll take a look as well.

**Comment by BerndWessels** [comment]
@guncha I had a look at your example and see now what you want to achieve.

But from my "limited" understanding of babel plugins, I would say that you can't introduce additional dependencies from a a babel plugin. But I would love if you could prove me wrong and find a way.
For now I think your best bet is to somehow make webpack aware of your schema.json and integrate it into its watch list.

I close this for now. Feel free to reopen it if you have any more insides or a solution to this problem.
Cheers
Bernd
