### ISSUE TITLE
Error because you are using 'template literals'

### ISSUE THREAD

**Issue by g1ibby** [BerndWessels/babel-relay-plugin-loader#9]
I have an error:

> [0] /home/swaribrus/Documents/isomorphic-material-relay-starter-kit/node_modules/babel-relay-plugin-loader/index.js:20
> [0]     console.log(`babel-relay-plugin-loader: using schema at [${schemaPath}]`);
> [0]                 ^
> [0] SyntaxError: Unexpected token ILLEGAL

I think it's because it uses 'template literals' (https://github.com/BerndWessels/babel-relay-plugin-loader/pull/7)

**Comment by BerndWessels** [comment]
Hi @suribit 

I haven't experienced any problem with it yet - but have only one way of using it myself.

I am happy to take PRs or make you a collaborator if you like to provide a fix.

Cheers
Bernd

**Comment by helielson** [comment]
I had the same problem using node 0.12.
Works well with node 4

**Comment by g1ibby** [comment]
Thank you. The problem was solved. Updated the version of node js
